name: Java App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: |
          cd department-service
          mvn clean package -DskipTests
          cd ../account-service
          mvn clean package -DskipTests
          cd ..

      - name: Docker Compose Cleanup
        run: |
          docker compose down || true

      - name: Docker Compose Build
        run: |
          docker compose build

      - name: Docker Compose Up
        run: |
          docker compose up -d

      - name: Start Java Application (auth-service)
        run: |
          cd auth-service
          ./gradlew bootRun &
